# Generated by Django 3.0 on 2022-08-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'customer'), ('cafe', 'cafe'), ('sysadmin', 'sysadmin')], default='customer', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
