# Generated by Django 3.0 on 2022-09-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cafe",
            unique_together={("name", "owner")},
        ),
        migrations.AlterField(
            model_name="cafe",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cafes",
                to="location.Address",
            ),
        ),
    ]
